app:
  hello:
    prefix: Merhabalar Sayin
  language: ex
application:
  info:
    build: 220
    desc: good application
    hello:
      prefix: Koniciva
    index: 10
    language: ex
    person-list:
    - height: 200
      name: osman
      surname: veli
      weight: 95
    - height: 180
      name: ali
      surname: veli
      weight: 85
    person-map:
      osmanyay:
        height: 200
        name: osman
        surname: yay
        weight: 100
    supported-language:
    - Turkish
    - English
    - Spanish
    - Japan
    version: 1.0.0
server:
  port: 9090
  http2:
    enabled: false
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always
      show-components: always
spring:
  profiles:
    default: eng
  task:
    scheduling:
      pool:
        size: 5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ''
    url: ENC(mdN63nFAcl360z+gQykQSbGX+8mpeEzTIQ/YEE1hd6BGXB+sIHm4xBsDuKQqK9ypcdsYu0QsOQR7Qu8SiIMILQWCUIy2UTu2yoQLzjlselX/oY4mi3PsFDG7xR3AFlTdkGwNNXYrk0KIne3LLTKMdaBBnlaFyDM1NUsg7aFILvA=)
    username: ENC(buf7D1/YHT+ezd9305kRJDyzepMoOfHfOsHPMPo3Y/6xtrQuQYEibi/z03bS9RrL)
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  security:
    user:
      name: osman
      password: 123456
      roles:
      - USER